seed: 42
ngpu: 4
verbose: True

directories:
  model: "/usr/project/xtmp/cs474_cv/ConceptWhitening/models/checkpoints/lambda_0_jul5_epoch_46_acc_0.8776.pth"
  checkpoint: "/usr/project/xtmp/cs474_cv/ConceptWhitening/models/checkpoints"
  eval: "/usr/project/xtmp/cs474_cv/ConceptWhitening/eval"
  data: "datasets/cub200_cw"
  high_concepts: "data/json/high_level.json"
  low_concepts: "data/json/low_level.json"
  mappings: "data/json/mappings.json"

optim:
  lr: 1.0e-3
  momentum: 0.9
  l2: 1.0e-5
  lr_step: 30
  lr_gamma: 0.2

cw_layer:
  whitened_layers: [[0], [0], [0], [0]]
  cw_lambda: 1
  activation_mode: "pool_max"

train:
  vanilla: False
  print_freq: 1
  train_cw_freq: 20
  epochs: 0
  batch_size: 128
  workers: 2
  checkpoint_prefix: "lambda_0_jul5"

eval:
  top_k_concepts: True
  k_concepts: 10
