seed: 42
ngpu: 4
verbose: True

directories:
  model: "/usr/project/xtmp/cs474_cv/ConceptWhitening/models/pretrained/iNaturalist2018_res50_180epoch.pth"
  checkpoint: "/usr/project/xtmp/cs474_cv/ConceptWhitening/models/checkpoints"
  eval: "/usr/project/xtmp/cs474_cv/ConceptWhitening/eval"
  data: "datasets/cub200_cw"
  high_concepts: "data/json/high_level.json"
  low_concepts: "data/json/low_level.json"
  mappings: "data/json/mappings.json"

optim:
  lr: 1.0e-3
  momentum: 0.9
  l2: 1.0e-5
  lr_step: 30
  lr_gamma: 0.2

cw_layer:
  whitened_layers: [[-1], [-1], [-1], [-1]]
  cw_lambda: 0.2
  activation_mode: "pool_max"

train:
  vanilla: True
  print_freq: 1
  train_cw_freq: 20
  epochs: 5
  batch_size: 128
  workers: 3
  checkpoint_prefix: "alex_jul18_beak_only"
  allowed_concepts: [1, 2, 3, 4, 5, 6, 7, 8, 9]

eval:
  top_k_concepts: True
  k_concepts: 50
